
import { ModuleId, ModuleData, Tool, PromptTemplate, GlossaryItem, CaseStudy } from './types';

export const PROMPT_LIBRARY: PromptTemplate[] = [
  {
    title: 'System Architectural Intent',
    category: 'Design',
    scenario: 'Defining a new full-stack system',
    template: 'I am building a [SYSTEM_NAME]. The core user flow is [STEP_1] to [STEP_2]. I value [SPEED/ACCURACY/ESTHETICS]. Generate the initial project structure, identifying key components and state management requirements. Use a modern tech stack (React, Tailwind, Supabase).'
  },
  {
    title: 'Deterministic Logic Manifest',
    category: 'Logic',
    scenario: 'Refining complex business logic',
    template: 'This function handles [PROCESS]. Currently, it fails when [EDGE_CASE]. Rewrite this to be deterministic, handle all edge cases explicitly, and include detailed logging for architectural debugging.'
  },
  {
    title: 'The Component Architect',
    category: 'Design',
    scenario: 'Building a complex UI component',
    template: 'Create a high-fidelity [COMPONENT_NAME] using Tailwind CSS. It must be fully accessible (ARIA), responsive, and support [DARK/LIGHT] modes. The component should handle these states: [LOADING/ERROR/EMPTY].'
  },
  {
    title: 'Database Schema Manifesto',
    category: 'Logic',
    scenario: 'Designing a data model',
    template: 'Design a relational database schema for [APP_TYPE]. Include tables for [ENTITIES]. Define relationships (1:N, M:N) and suggest Row Level Security (RLS) policies to ensure data sovereignty.'
  },
  {
    title: 'Agentic Bug Hunter',
    category: 'Debugging',
    scenario: 'Fixing a recurring system error',
    template: 'I am seeing [ERROR_MESSAGE] in [FILE]. Here is the current context and logs. Analyze the root cause across the system, not just the file, and provide a comprehensive fix that prevents regression.'
  },
  {
    title: 'API Waiter Specification',
    category: 'Logic',
    scenario: 'Connecting Frontend to Backend',
    template: 'Create a TypeScript service that acts as the waiter between my Frontend and [API_ENDPOINT]. It should handle authentication headers, retries with exponential backoff, and transform the raw data into [INTERFACE_NAME].'
  },
  {
    title: 'Refining Domain Expertise',
    category: 'Logic',
    scenario: 'Infusing specific knowledge',
    template: 'Review this feature. I am an expert in [DOMAIN]. The current implementation misses [SPECIFIC_NUANCE]. Rewrite the logic to prioritize [NUANCE] while maintaining performance.'
  },
  {
    title: 'Micro-Service Orchestration',
    category: 'Logic',
    scenario: 'Connecting multi-step flows',
    template: 'Design a workflow where a user upload triggers [SERVICE_A], which passes data to [SERVICE_B], and finally notifies [USER] via [CHANNEL]. Map the data transformations needed at each step.'
  },
  {
    title: 'Visual Vibe Refinement',
    category: 'Design',
    scenario: 'Tweaking CSS variables',
    template: 'The current UI feels too [ADJECTIVE]. Update the Tailwind config and CSS variables to make it feel [NEW_VIBE]. Focus on spacing, shadows, and subtle background gradients.'
  },
  {
    title: 'Edge Case Stress Test',
    category: 'Logic',
    scenario: 'Generating test scenarios',
    template: 'List 10 potential edge cases for a [FEATURE_NAME] system. For each, describe the expected system behavior and provide a Vitest test case outline.'
  }
];

export const GLOSSARY: GlossaryItem[] = [
  { term: 'Vibe Coding', definition: 'A development paradigm where human intent is the primary source of truth, and AI agents translate that intent into functional code across the full stack.' },
  { term: 'Probabilistic UI', definition: 'Interfaces generated by LLMs that may vary slightly in implementation but maintain the intended functional "vibe".' },
  { term: 'System Orchestration', definition: 'The act of managing multiple AI-driven services to work as a unified application.' },
  { term: 'Deterministic Logic', definition: 'Code that produces the same output every time given the same input, crucial for AI reliability.' }
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    title: 'FitVibe Tracker',
    description: 'A full-stack fitness app built in 4 hours.',
    vibe: 'Modern, high-energy dashboard with real-time data visualization.',
    outcome: 'Completed the MVP without writing a single manual CSS class.',
    imagePrompt: 'A futuristic fitness dashboard on a smartphone screen, vibrant neon blue and lime green accents, minimalist data charts, professional UI/UX photography.'
  },
  {
    title: 'AutoLegal AI',
    description: 'Document automation for small law firms.',
    vibe: 'Professional, trustworthy, high-contrast.',
    outcome: 'Reduced document processing time by 80% using Make.com and OpenAI.',
    imagePrompt: 'A sleek legal dashboard with high contrast typography, document icons floating, professional navy blue and white aesthetic, 4k render.'
  }
];

export const TOOLKIT: Tool[] = [
  { name: 'Cursor', category: 'IDEs', description: 'AI-native code editing.' },
  { name: 'Windsurf', category: 'IDEs', description: 'High-flow state agentic IDE.' },
  { name: 'v0.dev', category: 'Frontend', description: 'Natural language UI generator.' },
  { name: 'Lovable', category: 'Frontend', description: 'Full-stack GPT engineer.' },
  { name: 'Supabase', category: 'Backend', description: 'Instant data persistence.' },
  { name: 'Make.com', category: 'Automation', description: 'Visual API "Glue".' },
  { name: 'Bolt.new', category: 'Frontend', description: 'Browser-based prompt-to-app.' },
  { name: 'Replit Agent', category: 'Deployment', description: 'Autonomous app deployment.' },
  { name: 'Claude 3.7 Sonnet', category: 'Models', description: 'Top-tier logic and coding.' },
  { name: 'GPT-4o', category: 'Models', description: 'Vision and multi-modal intent.' },
  { name: 'Perplexity', category: 'Research', description: 'Real-time domain research.' },
  { name: 'Figma AI', category: 'Design', description: 'Generative design systems.' },
  { name: 'Resend', category: 'Communication', description: 'Developer-first email.' },
  { name: 'Upstash', category: 'Backend', description: 'Serverless state management.' },
  { name: 'Clerk', category: 'Backend', description: 'Auth and user management.' },
  { name: 'Aider', category: 'IDEs', description: 'CLI-based pair programming.' },
  { name: 'Continue.dev', category: 'IDEs', description: 'Open-source autopilot extension.' },
  { name: 'Linear', category: 'Planning', description: 'Architectural progress tracking.' },
  { name: 'Vercel', category: 'Deployment', description: 'Premier frontend platform.' },
  { name: 'Netlify', category: 'Deployment', description: 'Cloud frontend deployment.' },
  { name: 'Postman', category: 'Testing', description: 'API waiter logic testing.' },
  { name: 'Lucide', category: 'Assets', description: 'Minimalist UI icons.' },
  { name: 'Tailwind CSS', category: 'Frontend', description: 'Utility-first styling.' },
  { name: 'Shadcn/UI', category: 'Frontend', description: 'Standardized accessible components.' },
  { name: 'Prisma', category: 'Backend', description: 'Type-safe database ORM.' },
  { name: 'Stripe', category: 'Backend', description: 'Monetizing digital intent.' },
  { name: 'Pinecone', category: 'Backend', description: 'Long-term memory/RAG storage.' },
  { name: 'LangChain', category: 'Orchestration', description: 'Framework for building complex agentic workflows.' },
  { name: 'n8n', category: 'Automation', description: 'Workflow automation engine.' },
  { name: 'Railway', category: 'Deployment', description: 'Backend service hosting.' },
  { name: 'Whisper', category: 'AI Services', description: 'Speech-to-intent transcription.' },
  { name: 'ElevenLabs', category: 'AI Services', description: 'High-fidelity audio manifest.' },
  { name: 'Midjourney', category: 'Design', description: 'High-fidelity brand visuals.' },
  { name: 'Excalidraw', category: 'Design', description: 'Architectural sketching.' },
  { name: 'Drizzle ORM', category: 'Backend', description: 'Lightweight SQL-first ORM.' },
  { name: 'Firebase', category: 'Backend', description: 'Comprehensive mobile backend.' },
  { name: 'Playwright', category: 'Testing', description: 'Automated E2E validation.' },
  { name: 'Storybook', category: 'Frontend', description: 'UI component perfection.' },
  { name: 'Tally', category: 'Research', description: 'Data-collection manifests.' },
  { name: 'Arc Browser', category: 'Workspace', description: 'Architect-optimized browsing.' }
];

export const MODULES: ModuleData[] = [
  {
    id: ModuleId.Intro,
    title: 'Foundation: AI-Assisted Development',
    description: 'Vibe coding leverages AI to build apps based on product-specific knowledge and domain expertise.',
    lessons: [
      {
        title: 'The Power of AI in Dev',
        conceptTitle: 'Innovative Solutions',
        conceptAnalogy: 'Vibe Coding is being a master conductor. You don\'t need to play every instrument to ensure the symphony is perfect.',
        conceptDescription: 'Vibe coding leverages AI to build apps based on product-specific knowledge and domain expertise, not just general coding skills. The power of AI in development lies in applying creative problem-solving and specialized knowledge to produce innovative solutions.',
        instructions: [
          '➡ Adopt the identity of a "System Architect".',
          '➡ Apply creative problem-solving and specialized knowledge.',
          '➡ Understand that domain expertise is your most valuable asset.'
        ],
        visualGuideDescription: 'A brain connecting specialized domain nodes into a central AI processor.',
        imagePrompt: 'A futuristic clean laboratory with a central glowing core of "intent", data streams connecting to specialized industry icons.',
        videoUrl: 'https://www.youtube.com/embed/sdH7YPAmHes'
      }
    ],
    quiz: [
      { question: 'What is the core of Vibe Coding?', options: ['Manual typing speed', 'Applying domain expertise through AI', 'Using older hardware', 'Learning binary'], correctIndex: 1 },
      { question: 'Which role best describes the Vibe Coder?', options: ['The Syntax Scripter', 'The System Architect', 'The Manual Debugger', 'The Keyboard Warrior'], correctIndex: 1 },
      { question: 'Why is domain expertise prioritized over syntax mastery?', options: ['Because AI can handle syntax, but needs your unique creative intent', 'Because code doesn\'t matter anymore', 'Because domain experts have more money', 'Because syntax is illegal now'], correctIndex: 0 }
    ],
    checklist: [
      'Install Cursor or Windsurf',
      'Identify your specialized domain knowledge (e.g. Finance, Art)',
      'Draft your first System Architecture manifesto'
    ]
  },
  {
    id: ModuleId.Workspace,
    title: 'Module 2: Prompt Engineering',
    description: 'Creating a minimalist prompt with domain-specific research is the crucial first step.',
    lessons: [
      {
        title: 'Manifesting Intent',
        conceptTitle: 'The Specification Loop',
        conceptAnalogy: 'Writing a prompt is like briefing a master sculptor. You start with the rough shape and refine.',
        conceptDescription: 'Creating a minimalist prompt with domain-specific research is the crucial first step in vibe coding, outlining the problem and desired outcome. Vibe coding is an iterative process involving trial-and-error, checkpoints, and the ability to roll back changes when needed.',
        instructions: [
          '➡ Outline the problem and desired outcome clearly.',
          '➡ Conduct domain-specific research before writing.',
          '➡ Use checkpoints and prepare to roll back changes.'
        ],
        visualGuideDescription: 'Blueprints evolving from rough sketches to high-definition 3D models.',
        imagePrompt: 'A holographic architectural blueprint floating above a minimalist desk, pencil sketches morphing into digital circuits.',
        videoUrl: 'https://www.youtube.com/embed/Xq-v690hOks'
      }
    ],
    quiz: [
      { question: 'What is the primary purpose of a minimalist prompt?', options: ['To confuse the AI', 'To outline the core problem and desired outcome clearly', 'To save on API token costs only', 'To make the code shorter'], correctIndex: 1 },
      { question: 'What should you do if an Agent\'s output is incorrect?', options: ['Give up', 'Use the Specification Loop to refine intent or roll back context', 'Restart your computer', 'Blame the AI model'], correctIndex: 1 },
      { question: 'Why is research critical before prompting?', options: ['It isn\'t, just start typing', 'It provides the high-context domain knowledge the AI needs to be accurate', 'To find code to copy-paste', 'To waste time'], correctIndex: 1 }
    ],
    checklist: [
      'Perform 20 minutes of research on a specific domain problem',
      'Index your project context in your AI IDE',
      'Generate a feature using an iterative Specification Loop'
    ]
  },
  {
    id: ModuleId.Frontend,
    title: 'Module 3: AI Agents and Assistants',
    description: 'AI agents perform complex tasks like app building, while assistants handle lightweight edits.',
    lessons: [
      {
        title: 'The Agentic Workflow',
        conceptTitle: 'Agents vs. Assistants',
        conceptAnalogy: 'AI agents are your heavy lifting machinery; Assistants are your precision tools.',
        conceptDescription: 'AI agents can perform complex tasks like console interaction, screenshot analysis, and app building, while assistants handle lightweight edits and quick changes. The debugging process in vibe coding mimics traditional methods, using error logging and trial-and-error.',
        instructions: [
          '➡ Use Agents for complex tasks and full app construction.',
          '➡ Use Assistants for lightweight edits and quick changes.',
          '➡ Debug using error logging and iterative trial-and-error.'
        ],
        visualGuideDescription: 'A large robot building a wall and a small precise tool painting a detail.',
        imagePrompt: 'Dual robotic arms working in sync on a floating translucent screen, cybernetic laboratory setting.',
        videoUrl: 'https://www.youtube.com/embed/5pLp4ZzB8bM'
      }
    ],
    quiz: [
      { question: 'When is it best to use an AI Agent?', options: ['For changing a single hex color', 'For complex tasks like building full features or interacting with the console', 'For spell checking a comment', 'For watching videos'], correctIndex: 1 },
      { question: 'What distinguishes an AI Assistant from an Agent?', options: ['Assistants are faster but limited to simple text/code edits', 'Assistants are more expensive', 'Assistants can build entire apps autonomously', 'There is no difference'], correctIndex: 0 },
      { question: 'How is debugging typically handled in a Vibe Coding workflow?', options: ['By deleting all the code', 'By feeding error logs and console context back to the Agent', 'By switching to a different IDE', 'By manual binary inspection'], correctIndex: 1 }
    ],
    checklist: [
      'Instruct an Agent to build a multi-component page',
      'Use an Assistant to refine a single Tailwind class',
      'Perform a debugging loop using console logs as context'
    ]
  },
  {
    id: ModuleId.Backend,
    title: 'Module 4: Persistence & System Memory',
    description: 'Turn your visual Vibe into a living, data-driven system.',
    lessons: [
      {
        title: 'Logical Persistence',
        conceptTitle: 'System of Record',
        conceptAnalogy: 'The database is your system\'s memory.',
        conceptDescription: 'Data persistence ensures user intent is saved. Debugging here requires systematic error logging and an understanding of data flow from UI to Database.',
        instructions: [
          '➡ Define your data schema with architectural precision.',
          '➡ Connect your UI state to backend storage logic.',
          '➡ Monitor logs to ensure logical integrity.'
        ],
        visualGuideDescription: 'Data packets traveling into a secure, glowing vault.',
        imagePrompt: 'A vast digital vault with glowing data particles entering organized slots.',
        videoUrl: 'https://www.youtube.com/embed/S_I-vL_h5gY'
      }
    ],
    quiz: [
      { question: 'What is the primary role of a database in your app?', options: ['To make the app run faster', 'To serve as the persistent "System of Record" for user data', 'To generate images', 'To store only HTML'], correctIndex: 1 },
      { question: 'What does "Persistence" mean in software architecture?', options: ['Trying really hard', 'That data remains available even after the user closes the app', 'That the code is very long', 'That the app is always loading'], correctIndex: 1 },
      { question: 'What tool is commonly used to model database schemas via intent?', options: ['Photoshop', 'AI-assisted SQL manifests or ORM definitions (like Prisma/Drizzle)', 'Excel', 'A text file on the desktop'], correctIndex: 1 }
    ],
    checklist: [
      'Create a table schema using the "Database Schema Manifesto" prompt',
      'Connect a frontend button to a database insert operation',
      'Validate a data-read operation from the cloud'
    ]
  },
  {
    id: ModuleId.Automation,
    title: 'Module 5: System Orchestration',
    description: 'Connecting the pieces into an intelligent ecosystem.',
    lessons: [
      {
        title: 'The Glue of Automation',
        conceptTitle: 'Digital Orchestration',
        conceptAnalogy: 'Automation is setting up a domino rally.',
        conceptDescription: 'Tools like Make.com connect disparate services, allowing intent to scale automatically across the digital ecosystem.',
        instructions: [
          '➡ Identify system triggers and downstream actions.',
          '➡ Use automation to bridge gaps between different APIs.',
          '➡ Ensure failure handling is built into the orchestration.'
        ],
        visualGuideDescription: 'Interconnected gears glowing as they turn.',
        imagePrompt: 'An intricate web of glowing lines connecting floating icons in a dark void.',
        videoUrl: 'https://www.youtube.com/embed/1BNo0N8_D70'
      }
    ],
    quiz: [
      { question: 'In automation, what is a "Trigger"?', options: ['The final step of a process', 'An event that initiates a sequence of actions', 'A piece of code that causes an error', 'A button the user never clicks'], correctIndex: 1 },
      { question: 'What is "The Glue" in modern system architecture?', options: ['Physical adhesive', 'Tools like Make.com or n8n that connect disparate APIs and services', 'The CSS code', 'The browser window'], correctIndex: 1 },
      { question: 'What is a major benefit of System Orchestration?', options: ['It makes the app look better', 'It allows your application\'s intent to scale across multiple services automatically', 'It reduces the number of colors you can use', 'It makes the code harder to read'], correctIndex: 1 }
    ],
    checklist: [
      'Map out a 3-step automation workflow',
      'Build a trigger-action chain in Make.com or n8n',
      'Test the end-to-end orchestration'
    ]
  },
  {
    id: ModuleId.FinalProject,
    title: 'Module 6: Development and Deployment',
    description: 'Deployment involves the AI agent bundling the entire environment and making it live.',
    lessons: [
      {
        title: 'The Cloud Launch',
        conceptTitle: 'Live Manifestation',
        conceptAnalogy: 'Deployment is the rocket launch.',
        conceptDescription: 'Deployment in vibe coding involves the AI agent bundling the entire environment and making it live on the web. Replit provides a cloud-based live development environment, enabling access from mobile devices. Redeployment is necessary for updates.',
        instructions: [
          '➡ Bundle the entire environment for live web access.',
          '➡ Use cloud environments for mobile interaction.',
          '➡ Redeploy regularly to manifest project updates.'
        ],
        visualGuideDescription: 'A rocket launch of code into a cloud nebula.',
        imagePrompt: 'A digital rocket made of code launching into a vast, glowing purple cloud network.',
        videoUrl: 'https://www.youtube.com/embed/v7X_O5h2I9Y'
      }
    ],
    quiz: [
      { question: 'What is required to make updates to a deployed application?', options: ['Restarting the server', 'Redeployment of the updated bundle', 'Buying a new domain name', 'Waiting for a week'], correctIndex: 1 },
      { question: 'Why use a cloud-based environment like Replit or Vercel for deployment?', options: ['To hide the code', 'To ensure instant mobile accessibility and a live production URL', 'Because local files are dangerous', 'To make the app slower'], correctIndex: 1 },
      { question: 'What is the final step of a professional Vibe Coding launch?', options: ['A "Vibe Audit" to ensure all intended logical flows function as expected in production', 'Deleting the source code', 'Writing a manual README in binary', 'Changing the app name'], correctIndex: 0 }
    ],
    checklist: [
      'Deploy your final project to a live URL',
      'Verify mobile access and UI responsiveness',
      'Share your manifested product with the community'
    ]
  }
];
