
import { ModuleId, ModuleData, Tool, PromptTemplate, GlossaryItem, CaseStudy } from './types';

export const PROMPT_LIBRARY: PromptTemplate[] = [
  {
    title: 'System Architectural Intent',
    category: 'Design',
    scenario: 'Defining a new full-stack system',
    template: 'I am building a [SYSTEM_NAME]. The core user flow is [STEP_1] to [STEP_2]. I value [SPEED/ACCURACY/ESTHETICS]. Generate the initial project structure, identifying key components and state management requirements. Use a modern tech stack (React, Tailwind, Supabase).'
  },
  {
    title: 'Deterministic Logic Manifest',
    category: 'Logic',
    scenario: 'Refining complex business logic',
    template: 'This function handles [PROCESS]. Currently, it fails when [EDGE_CASE]. Rewrite this to be deterministic, handle all edge cases explicitly, and include detailed logging for architectural debugging.'
  },
  {
    title: 'The Component Architect',
    category: 'Design',
    scenario: 'Building a complex UI component',
    template: 'Create a high-fidelity [COMPONENT_NAME] using Tailwind CSS. It must be fully accessible (ARIA), responsive, and support [DARK/LIGHT] modes. The component should handle these states: [LOADING/ERROR/EMPTY].'
  },
  {
    title: 'Database Schema Manifesto',
    category: 'Logic',
    scenario: 'Designing a data model',
    template: 'Design a relational database schema for [APP_TYPE]. Include tables for [ENTITIES]. Define relationships (1:N, M:N) and suggest Row Level Security (RLS) policies to ensure data sovereignty.'
  },
  {
    title: 'Agentic Bug Hunter',
    category: 'Debugging',
    scenario: 'Fixing a recurring system error',
    template: 'I am seeing [ERROR_MESSAGE] in [FILE]. Here is the current context and logs. Analyze the root cause across the system, not just the file, and provide a comprehensive fix that prevents regression.'
  },
  {
    title: 'API Waiter Specification',
    category: 'Logic',
    scenario: 'Connecting Frontend to Backend',
    template: 'Create a TypeScript service that acts as the waiter between my Frontend and [API_ENDPOINT]. It should handle authentication headers, retries with exponential backoff, and transform the raw data into [INTERFACE_NAME].'
  },
  {
    title: 'Dark Mode Logic Integration',
    category: 'Design',
    scenario: 'Applying global theme vibes',
    template: 'Implement a robust theme switching system. The vibe should be "Midnight Professional" for dark mode and "Clean Canvas" for light mode. Provide the Tailwind config and the React context provider.'
  },
  {
    title: 'Mobile Optimization Audit',
    category: 'Design',
    scenario: 'Refining for small screens',
    template: 'Review the provided UI code. Identify three areas where mobile usability is compromised. Rewrite the components to use a mobile-first approach, ensuring touch targets are at least 44px.'
  },
  {
    title: 'Test Suite Manifestation',
    category: 'Logic',
    scenario: 'Ensuring system stability',
    template: 'Generate a suite of Vitest or Jest tests for [FUNCTION_NAME]. Cover the happy path, boundary conditions, and invalid inputs. Mock all external API calls to ensure deterministic testing.'
  },
  {
    title: 'Accessibility Compliance Refactor',
    category: 'Design',
    scenario: 'Meeting WCAG standards',
    template: 'Refactor the following HTML/React snippet to meet WCAG 2.1 AA standards. Ensure proper heading hierarchy, alt text for images, and keyboard focus management for all interactive elements.'
  },
  {
    title: 'Automated Documentation Generator',
    category: 'Logic',
    scenario: 'Explaining code to human architects',
    template: 'Analyze [FILE_PATH]. Generate professional documentation including a high-level summary, a list of exported functions with parameters/return types, and a "Vibe Overview" explaining the intent.'
  }
];

export const GLOSSARY: GlossaryItem[] = [
  { term: 'Vibe Coding', definition: 'The collapse of the barrier between human creative intent and digital manifestation via high-context agentic reasoning.' },
  { term: 'Probabilistic UI', definition: 'Interfaces generated by LLMs that may vary slightly in implementation but maintain the intended functional "vibe".' },
  { term: 'System Orchestration', definition: 'The act of managing multiple AI-driven services to work as a unified application.' },
  { term: 'Deterministic Logic', definition: 'Code that produces the same output every time given the same input, crucial for AI reliability.' }
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    title: 'FitVibe Tracker',
    description: 'A full-stack fitness app built in 4 hours.',
    vibe: 'Modern, high-energy dashboard with real-time data visualization.',
    outcome: 'Completed the MVP without writing a single manual CSS class.',
    imagePrompt: 'A futuristic fitness dashboard on a smartphone screen, vibrant neon blue and lime green accents, minimalist data charts, professional UI/UX photography.'
  },
  {
    title: 'AutoLegal AI',
    description: 'Document automation for small law firms.',
    vibe: 'Professional, trustworthy, high-contrast.',
    outcome: 'Reduced document processing time by 80% using Make.com and OpenAI.',
    imagePrompt: 'A sleek legal dashboard with high contrast typography, document icons floating, professional navy blue and white aesthetic, 4k render.'
  }
];

export const TOOLKIT: Tool[] = [
  { name: 'Cursor', category: 'IDEs', description: 'The current industry leader for AI-native code editing.' },
  { name: 'Windsurf', category: 'IDEs', description: 'Agentic IDE designed for high-flow state development.' },
  { name: 'v0.dev', category: 'Frontend', description: 'Vercel\'s engine for generating UI from natural language.' },
  { name: 'Lovable', category: 'Frontend', description: 'Full-stack GPT engineer for rapid application manifest.' },
  { name: 'Supabase', category: 'Backend', description: 'Postgres-based backend for instant data persistence.' },
  { name: 'Make.com', category: 'Automation', description: 'The visual "Glue" for connecting disparate system APIs.' },
  { name: 'Bolt.new', category: 'Frontend', description: 'Prompt-to-app generator for instant browser-based dev.' },
  { name: 'Replit Agent', category: 'Deployment', description: 'Autonomous agent that builds and deploys full-stack apps.' },
  { name: 'Claude 3.7 Sonnet', category: 'Models', description: 'The gold standard for coding logic and architectural reasoning.' },
  { name: 'GPT-4o', category: 'Models', description: 'Versatile multi-modal model for vision and general intent.' },
  { name: 'Perplexity', category: 'Research', description: 'Real-time research engine for domain-specific knowledge.' },
  { name: 'Figma AI', category: 'Design', description: 'Generates design systems and layouts for visual vibes.' },
  { name: 'Resend', category: 'Communication', description: 'The professional standard for developer-first email delivery.' },
  { name: 'Upstash', category: 'Backend', description: 'Serverless Redis/Kafka for low-latency system state.' },
  { name: 'Clerk', category: 'Authentication', description: 'Comprehensive user management and auth manifest.' },
  { name: 'Aider', category: 'CLI Tools', description: 'Powerful command-line chat for pair programming.' },
  { name: 'Continue.dev', category: 'IDEs', description: 'Open-source autopilot extension for VS Code/JetBrains.' },
  { name: 'Linear', category: 'Planning', description: 'The streamlined tool for tracking architectural progress.' },
  { name: 'Vercel', category: 'Deployment', description: 'The premier platform for frontend and edge function manifest.' },
  { name: 'Netlify', category: 'Deployment', description: 'High-speed cloud platform for modern web projects.' },
  { name: 'Postman', category: 'Testing', description: 'The foundational tool for testing API waiter logic.' },
  { name: 'Lucide', category: 'Assets', description: 'Beautiful, minimalist icon sets for UI building blocks.' },
  { name: 'Tailwind CSS', category: 'Frontend', description: 'The utility-first framework for visual manifest.' },
  { name: 'Shadcn/UI', category: 'Frontend', description: 'Standardized accessible component architecture.' },
  { name: 'Prisma', category: 'Backend', description: 'Next-generation ORM for intuitive database modeling.' },
  { name: 'Stripe', category: 'Payments', description: 'The standard for monetizing digital intent.' },
  { name: 'Pinecone', category: 'Vector DB', description: 'Memory bank for long-term AI context and RAG.' },
  { name: 'LangChain', category: 'Orchestration', description: 'Framework for building complex agentic workflows.' },
  { name: 'n8n', category: 'Automation', description: 'Self-hosted workflow automation for data sovereignty.' },
  { name: 'Railway', category: 'Deployment', description: 'Simple, powerful cloud platform for backend services.' },
  { name: 'OpenAI Whisper', category: 'AI Services', description: 'World-class speech-to-intent transcription.' },
  { name: 'ElevenLabs', category: 'AI Services', description: 'High-fidelity audio manifest for system voices.' },
  { name: 'Midjourney', category: 'Design', description: 'High-fidelity visual vibe generation for branding.' },
  { name: 'Excalidraw', category: 'Design', description: 'Virtual whiteboard for sketching system architecture.' },
  { name: 'Drizzle ORM', category: 'Backend', description: 'Lightweight, fast SQL-first database modeling.' },
  { name: 'Firebase', category: 'Backend', description: 'Comprehensive platform for mobile and web manifest.' },
  { name: 'Playwright', category: 'Testing', description: 'Automated E2E testing for architectural validation.' },
  { name: 'Storybook', category: 'Frontend', description: 'Isolated environment for perfecting UI building blocks.' },
  { name: 'Tally', category: 'Research', description: 'The simplest way to manifest data-collection forms.' },
  { name: 'Arc Browser', category: 'Workspace', description: 'The optimized workspace for modern system architects.' }
];

export const MODULES: ModuleData[] = [
  {
    id: ModuleId.Intro,
    title: 'Foundation: The Vibe Coding Manifesto',
    description: 'Vibe coding leverages AI to build apps based on product-specific knowledge and domain expertise, not just general coding skills.',
    lessons: [
      {
        title: 'AI-Assisted Development',
        conceptTitle: 'Intent-First Development',
        conceptAnalogy: 'Vibe Coding is being a master conductor. You don\'t need to play every instrument to ensure the symphony is perfect.',
        conceptDescription: 'Vibe coding leverages AI to build apps based on product-specific knowledge and domain expertise, not just general coding skills. The power of AI in development lies in applying creative problem-solving and specialized knowledge to produce innovative solutions.',
        instructions: [
          '➡ Adopt the identity of a "System Architect".',
          '➡ Apply creative problem-solving and specialized knowledge.',
          '➡ Understand that domain expertise is your most valuable asset.'
        ],
        visualGuideDescription: 'A central brain emitting light beams (Intent) that pass through a digital prism (AI) to create a complex skyscraper (Software).',
        imagePrompt: 'A futuristic clean laboratory with a central glowing core of "intent", data streams connecting to specialized industry icons, ultra-modern 3D render.',
        videoUrl: 'https://www.youtube.com/embed/sdH7YPAmHes'
      }
    ],
    quiz: [
      { question: 'What is the core of AI-Assisted Development in Vibe Coding?', options: ['Typing faster', 'Applying domain expertise through AI', 'Using older hardware', 'Writing manual binary'], correctIndex: 1 }
    ]
  },
  {
    id: ModuleId.Workspace,
    title: 'Module 2: Prompt Engineering',
    description: 'Creating a minimalist prompt with domain-specific research is the crucial first step in vibe coding.',
    lessons: [
      {
        title: 'Manifesting Intent via Prompts',
        conceptTitle: 'The Specification Loop',
        conceptAnalogy: 'Vibe coding is an iterative process involving trial-and-error, checkpoints, and the ability to roll back changes.',
        conceptDescription: 'Creating a minimalist prompt with domain-specific research is the crucial first step in vibe coding, outlining the problem and desired outcome. It is a cycle of trial-and-error where you refine the "Vibe" until it meets the standard.',
        instructions: [
          '➡ Outline the problem and desired outcome clearly.',
          '➡ Conduct domain-specific research before writing your first prompt.',
          '➡ Use checkpoints and prepare to roll back changes when needed.'
        ],
        visualGuideDescription: 'A series of blueprints evolving from rough sketches to high-definition 3D models.',
        imagePrompt: 'A holographic architectural blueprint floating above a minimalist desk, pencil sketches morphing into digital circuits, professional workspace aesthetic.',
        videoUrl: 'https://www.youtube.com/embed/Xq-v690hOks'
      }
    ],
    quiz: [
      { question: 'What is a "minimalist prompt" for?', options: ['Saving money', 'Outlining the problem and desired outcome with domain research', 'Hiding code', 'Playing games'], correctIndex: 1 }
    ]
  },
  {
    id: ModuleId.Frontend,
    title: 'Module 3: AI Agents and Assistants',
    description: 'AI agents can perform complex tasks like console interaction and app building, while assistants handle lightweight edits.',
    lessons: [
      {
        title: 'The Agentic Workflow',
        conceptTitle: 'Agents vs. Assistants',
        conceptAnalogy: 'AI agents are your heavy lifting machinery; Assistants are your precision tools.',
        conceptDescription: 'AI agents can perform complex tasks like console interaction, screenshot analysis, and app building. Assistants handle lightweight edits and quick changes. The debugging process in vibe coding mimics traditional methods, using error logging and trial-and-error.',
        instructions: [
          '➡ Use Agents for complex tasks and full app construction.',
          '➡ Use Assistants for lightweight edits and quick changes.',
          '➡ Debug using error logging and iterative trial-and-error.'
        ],
        visualGuideDescription: 'A split screen showing a large robot building a wall (Agent) and a small precise tool painting a detail (Assistant).',
        imagePrompt: 'Dual robotic arms working in sync on a floating translucent screen, one large and powerful, one small and precise, cybernetic laboratory setting.',
        videoUrl: 'https://www.youtube.com/embed/5pLp4ZzB8bM'
      }
    ],
    quiz: [
      { question: 'What is a core capability of an AI Agent?', options: ['Only spell checking', 'Complex tasks like console interaction and app building', 'Physical repair', 'Deleting files'], correctIndex: 1 }
    ]
  },
  {
    id: ModuleId.Backend,
    title: 'Module 4: Persistence & System Memory',
    description: 'The Engine Room. Turn your visual Vibe into a living, data-driven system.',
    lessons: [
      {
        title: 'Logical Persistence',
        conceptTitle: 'System of Record',
        conceptAnalogy: 'A database is a library where your application stores its memories.',
        conceptDescription: 'Data persistence means your users can log back in and find their data. Debugging in this environment requires systematic error logging and architectural refinement.',
        instructions: [
          '➡ Define your data schema with architectural precision.',
          '➡ Connect your UI state to backend storage logic.',
          '➡ Monitor logs to ensure logical integrity.'
        ],
        visualGuideDescription: 'A vast digital vault with glowing data particles entering organized slots.',
        imagePrompt: 'A vast digital vault with glowing data particles entering organized slots, deep blue and teal lighting, cinematic perspective.',
        videoUrl: 'https://www.youtube.com/embed/S_I-vL_h5gY'
      }
    ],
    quiz: [
      { question: 'Why is persistence vital?', options: ['It looks cool', 'It ensures data is saved across sessions', 'It makes the font bigger', 'It is not vital'], correctIndex: 1 }
    ]
  },
  {
    id: ModuleId.Automation,
    title: 'Module 5: System Orchestration',
    description: 'Connecting the pieces. Learn to make your app part of a larger, intelligent ecosystem.',
    lessons: [
      {
        title: 'The Glue of Automation',
        conceptTitle: 'Digital Orchestration',
        conceptAnalogy: 'Automation is like a domino rally. One event triggers a thousand reactions.',
        conceptDescription: 'We use tools like Make.com to connect apps. It allows our intent to scale across services automatically, creating a unified systemic "Vibe".',
        instructions: [
          '➡ Identify system triggers and downstream actions.',
          '➡ Use automation to bridge gaps between different APIs.',
          '➡ Ensure failure handling is built into the orchestration.'
        ],
        visualGuideDescription: 'Interconnected gears glowing as they turn, each gear representing a different service.',
        imagePrompt: 'An intricate web of glowing fiber optic lines connecting various floating application icons in a dark void, energy pulses moving through the lines.',
        videoUrl: 'https://www.youtube.com/embed/1BNo0N8_D70'
      }
    ],
    quiz: [
      { question: 'What does "The Glue" represent?', options: ['Physical sticky stuff', 'Tools that connect different apps and services', 'The keyboard', 'The mouse'], correctIndex: 1 }
    ]
  },
  {
    id: ModuleId.FinalProject,
    title: 'Module 6: Development and Deployment',
    description: 'Deployment involves the AI agent bundling the entire environment and making it live on the web.',
    lessons: [
      {
        title: 'The Cloud Launch',
        conceptTitle: 'Live Manifestation',
        conceptAnalogy: 'Deployment is the rocket launch. You bundle your system and send it into the orbit of the public internet.',
        conceptDescription: 'Deployment in vibe coding involves the AI agent bundling the entire environment and making it live on the web. Replit provides a cloud-based live development environment, enabling access from mobile devices. Redeployment is necessary for updates.',
        instructions: [
          '➡ Bundle the entire environment for live web access.',
          '➡ Use cloud environments like Replit for mobile interaction.',
          '➡ Redeploy regularly to manifest project updates.'
        ],
        visualGuideDescription: 'A "Deploy" button being pressed, followed by a rocket-like launch of code into a cloud nebula.',
        imagePrompt: 'A digital rocket made of code launching into a vast, glowing purple cloud network, 4k resolution, cinematic lighting.',
        videoUrl: 'https://www.youtube.com/embed/v7X_O5h2I9Y'
      }
    ],
    quiz: [
      { question: 'What is necessary for project updates in a deployed app?', options: ['Deleting the account', 'Redeployment', 'Buying a new domain', 'Waiting for a week'], correctIndex: 1 }
    ]
  }
];
